# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3de21b95f269f271c56aa6ec1cc9b40a0890caafd879ae229e7f02858c6a0301be8d7de64cc5e4a36b3dd23753639b9d7b7c9d4768ac9cf2705cdf7969bc3f54

test:
  secret_key_base: 348f4aa65574b10905c36bac47f2557dc30026619aea32b3abdd50eb30736ab6c3ba58c3023e14fdce996c177b7d561229a4b3b072ef3f41755d6f62b422bab0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
